name: Clojure CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Scan
      uses: clj-holmes/clj-holmes-action@main
      with:
        output-type: 'sarif'
        output-file: 'result.sarif'
        fail-on-result: 'false'
    - name: Scan
      uses: clj-holmes/clj-holmes-action@main
      with:
        output-type: 'stdout'
        output-file: 'result.sarif'
        fail-on-result: 'false'

    - name: Generate Security Report
      uses: peter-murray/github-security-report-action@v2
      with:
        token: ${{ secrets.SECURITY_TOKEN }}
        sarifReportDir: 'result.sarif'
