name: Clojure CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein update-in :dependencies conj "[org.clojars.clj-holmes/clj-holmes \"0.1.1\"]" -- run -m clj-holmes.entrypoint .
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: report.sarif
